sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/gateway-server -f ./server/Dockerfile ./server

script:
  - docker run -e CI=true $DOCKER_ID/gateway-server npm run test base-validator.test

after_success:
  - docker build -t "$DOCKER_ID"/client ./client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" — password-stdin
  - docker push $DOCKER_ID/client
  - docker push $DOCKER_ID/server
