sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t juniorpazformoso/gateway-server:1.0 -f ./server/Dockerfile ./server
  - docker build -t juniorpazformoso/gateway-client:1.0 -f ./client/Dockerfile ./client

script:
  - docker run -e CI=true juniorpazformoso/gateway-server:1.0 npm run test

after_success:
  - docker login --username=$DOCKER_ID --password=$DOCKER_PASSWORD
  - docker push juniorpazformoso/gateway-client:1.0
  - docker push juniorpazformoso/gateway-server:1.0
